# Generated by Django 5.0.7 on 2024-07-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=255)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isEditable', models.BooleanField(default=False)),
            ],
        ),
    ]
